### ISSUE TITLE
Doubt regarding the Hamiltonian calculations for RHVAE model.

### ISSUE THREAD

**Issue by shikhar2333** [clementchadebec/benchmark_VAE#10]
In the paper, Hamiltonian is defined as follows:
```
H(z, v) = U(z) + K(v)  = -0.5*log(det(G^-1(z)) + 0.5*v^T*v
```
But in the code, I see extra terms like addition of a joint probability term and a **G** inverse multiplied in the term for kinetic energy.
Are these 2 equations equivalent?

**Comment by clementchadebec** [comment]
Oops, sorry for that, this one should work https://arxiv.org/abs/2010.11518

**Comment by clementchadebec** [comment]
We use the Cholesky decomposition of the metric G = LL^T allowing to sample from multivariate Gaussian distributions. Note that G(z) is a symmetric definite positive matrix

**Comment by shikhar2333** [comment]
So are M and G equivalent, since M is also defined as LL^T.

**Comment by shikhar2333** [comment]
Is E[P(x|z)] (where  z~q(z|x) and E denotes the expectation value) approximated by MSE/BCE loss in the implementation?

**Comment by clementchadebec** [comment]
Yes exactly. The MSE (resp. BCE loss) actually represents the opposite log-likelihood of a constant variance Gaussian distribution (resp. Bernoulli distribution) that are usually chosen for p(x|z) depending on the modeling of your data.

**Comment by shikhar2333** [comment]
Thanks for the confirmation. 
On a side note, i was wondering whether any conditional input was required in the VAE when you trained on the MRI data, since the dimensionality of the data would be high since it's a 3D input.

**Comment by clementchadebec** [comment]
The updated metric is needed during validation.
