### ISSUE TITLE
Model architecture used for the ADNI dataset.

### ISSUE THREAD

**Issue by shikhar2333** [clementchadebec/benchmark_VAE#11]
What was the model architecture for the RHVAE when the model was trained on the ADNI dataset?
Since the input size is ```84 x 104 x 89```, the model can't be too deep otherwise one might run into memory issues.

**Comment by clementchadebec** [comment]
Hello @shikhar2333,
You can find all the neural nets used in the appendices of the paper (from page 19 to 25).
I hope this helps.
