### ISSUE TITLE
Encoder class in BaseAE is 'BaseDecoder'

### ISSUE THREAD

**Issue by jdauvill** [clementchadebec/benchmark_VAE#110]
Hi,  - Thanks for this nice package !

Just came across a small bug, apparently: In the definition of the BaseAE class, the class for the encoder is declared as 'BaseDecoder', where it should probably be 'Base**En**coder':                                   

https://github.com/clementchadebec/benchmark_VAE/blob/b7c53f4ef9807ffb10907e0fba159571244a87c5/src/pythae/models/base/base_model.py#L60

Fortunately, the corresponding declaration in child classes (e.g. AE, VAE) seems correct.

Cheers,
Jérôme

**Comment by clementchadebec** [comment]
Hi @jdauvill ,

Thank you for opening this issue. This is indeed a typo. Nice catch! Do not hesitate to open a PR if you want to contribute. :) Otherwise, I will fix the typo this weekend.

Best,

Clément
