### ISSUE TITLE
Embed function returning different results

### ISSUE THREAD

**Issue by ErfanMowlaei** [clementchadebec/benchmark_VAE#126]
I've been using PVAE model for a while and I noticed that the (BaseAE) model's `embed` method returns different results for the same input(s) (during training or evaluation mode). I had to switch to `encoder(input).embedding` to get the right output. I am not sure why this behavior happens but it sure was messing with our experiments.

**Comment by clementchadebec** [comment]
Hi @ErfanMowlaei, 

Thank you for opening this issue. Actually, the `embed` method outputs a sample from the posterior distribution $q(z|x)$ associated to a given input $x$. Hence, the stochasticity in the output that you get. If you are only interested in a one-to-one mapping you can use the mean of $q(z|x)$ as a latent representation of your input, exactly as you do by calling `self.encoder(x).embedding`.
Do not hesitate if you have any questions l.

Best,

Clément

**Comment by ErfanMowlaei** [comment]
Hi @clementchadebec ,

Thank you for the clarification!
