### ISSUE TITLE
Estimation of log likelihood of q(z|x).

### ISSUE THREAD

**Issue by shikhar2333** [clementchadebec/benchmark_VAE#13]
In the code, the log likelihood for q(z|x) is computed as:
```
logq = normal.log_prob(eps0) - 0.5 * log_var.sum(dim=1)
```
Since q is distributed as N(mu, sigma), log likelihood function becomes:

<img src="http://latex.codecogs.com/svg.latex?-0.5*[ln\(|\Sigma|)&space;&plus;&space;(x&space;-&space;\mu&space;)'\Sigma^{-1}(x&space;-&space;\mu)&space;&plus;&space;kln2\pi&space;&space;]=&space;-0.5[\sum_{i=1}^{d}&space;log(\sigma&space;^{2}_{i})&space;&space;&plus;&space;(\Sigma&space;\epsilon)'\Sigma^{-1}(\Sigma&space;\epsilon)&space;&plus;&space;klog2\pi]=&space;&space;-0.5[\sum_{i=1}^{d}&space;log(\sigma&space;^{2}_{i})&space;&plus;&space;\sum_{i=1}^{d}\epsilon_{i}^{2}\sigma_{i}^{2}&space;&plus;&space;klog2\pi]" title="http://latex.codecogs.com/svg.latex?-0.5*[ln\(|\Sigma|) + (x - \mu )'\Sigma^{-1}(x - \mu) + kln2\pi ]= -0.5[\sum_{i=1}^{d} log(\sigma ^{2}_{i}) + (\Sigma \epsilon)'\Sigma^{-1}(\Sigma \epsilon) + klog2\pi]= -0.5[\sum_{i=1}^{d} log(\sigma ^{2}_{i}) + \sum_{i=1}^{d}\epsilon_{i}^{2}\sigma_{i}^{2} + klog2\pi]" />

The summation of log variances matches with the equation used in code, but the remaining expression doesn't match with the code.
Am i missing something?

**Comment by clementchadebec** [comment]
Hello,
Actually, these calculations are equivalent
```python
import torch
import torch.distributions as dist
mu = torch.randn(10, 3)
log_var = torch.randn(10, 3)
multi_variate_gauss = dist.MultivariateNormal(loc=mu, covariance_matrix=torch.diag_embed(log_var.exp())) # define N(mu, sigma)
normal = dist.MultivariateNormal(loc=torch.zeros_like(mu), covariance_matrix=torch.eye(3)) # define N(0, I)
eps = torch.rand_like(mu) # reparametrization trick
z = mu + torch.exp(0.5 * log_var) * eps # reparametrization trick
meth_1 = multi_variate_gauss.log_prob(z) # log-likelihood (method 1)
meth_2 = normal.log_prob(eps) - 0.5 * log_var.sum(dim=-1) # log-likelihood (method 2)
torch.allclose(meth_1, meth_2)
# Returns True
```
I hope this helps
