### ISSUE TITLE
nan in training loss when I run RHVAE tutorial on my local machine

### ISSUE THREAD

**Issue by axu-git** [clementchadebec/benchmark_VAE#132]
**Describe the bug**
I am training using the RHVAE colab code in a Jupyter notebook on my local machine. When the code is almost complete with epoch 14, I get an error saying there are a bunch of nans.

**To Reproduce**
1. Create a Jupyter notebook within a pip environment. 
2. Make with the following changes to reduce runtime:
```
num_train = 10000
num_eval = 2500
train_dataset = mnist_trainset.data[0:num_train].reshape(-1, 1, 28, 28) / 255.
eval_dataset = mnist_trainset.data[num_train:num_train + num_eval].reshape(-1, 1, 28, 28) / 255.
...
steps_saving=2
...
num_epochs=25
```
3. Run
```
pipeline(
    train_data=train_dataset,
    eval_data=eval_dataset
)
```
Here is what I get:

> ArithmeticError: NaN detected in train loss

**Expected behavior**
I expect the training to complete without errors.

**Desktop (please complete the following information):**
pythae version 0.1.2

**Additional context**
Same setup as issue I submitted [here](https://github.com/clementchadebec/benchmark_VAE/issues/131), but I get a different kind of nan error (hence a separate issue) when I ran the code again (training loss error vs value error). The only difference between setup here and the one in the link above is that I added `steps_saving=2`.

> ---------------------------------------------------------------------------
> ArithmeticError                           Traceback (most recent call last)
> Cell In[3], line 1
> ----> 1 pipeline(
>       2     train_data=train_dataset,
>       3     eval_data=eval_dataset
>       4 )
> 
> File ~/coding/conda_and_pip_envs_x86/gps_pip_x64/lib/python3.11/site-packages/pythae/pipelines/training.py:247, in TrainingPipeline.__call__(self, train_data, eval_data, callbacks)
>     243     raise ValueError("The provided training config is not supported.")
>     245 self.trainer = trainer
> --> 247 trainer.train()
> 
> File ~/coding/conda_and_pip_envs_x86/gps_pip_x64/lib/python3.11/site-packages/pythae/trainers/base_trainer/base_trainer.py:448, in BaseTrainer.train(self, log_output_dir)
>     439 self.callback_handler.on_epoch_begin(
>     440     training_config=self.training_config,
>     441     epoch=epoch,
>     442     train_loader=self.train_loader,
>     443     eval_loader=self.eval_loader,
>     444 )
>     446 metrics = {}
> --> 448 epoch_train_loss = self.train_step(epoch)
>     449 metrics["train_epoch_loss"] = epoch_train_loss
>     451 if self.eval_dataset is not None:
> 
> File ~/coding/conda_and_pip_envs_x86/gps_pip_x64/lib/python3.11/site-packages/pythae/trainers/base_trainer/base_trainer.py:627, in BaseTrainer.train_step(self, epoch)
>     624     epoch_loss += loss.item()
>     626     if epoch_loss != epoch_loss:
> --> 627         raise ArithmeticError("NaN detected in train loss")
>     629     self.callback_handler.on_train_step_end(
>     630         training_config=self.training_config
>     631     )
>     633 # Allows model updates if needed
> 
> ArithmeticError: NaN detected in train loss

**Comment by clementchadebec** [comment]
Hi @axu-git,

Can you try reducing the learning rate and/or the batch size?

Best,

Clément

**Comment by clementchadebec** [comment]
Hey, happy to see that this solved the issue. Yes it means that the gradient update make the parameters deviate too much and creates instabilities during training.
