### ISSUE TITLE
Integrate with Pytorch Lightning

### ISSUE THREAD

**Issue by axu-git** [clementchadebec/benchmark_VAE#133]
Thanks for the great repo! 

Are there plans to incorporate Pytorch Lightning? There's nothing wrong with pythae or anything like that; I know a lot of projects in Pytorch use Lightning and was curious if there are future plans to incorporate it.

**Comment by clementchadebec** [comment]
Hello @axu-git,

Thanks for the kind words. Actually, I do not plan to integrate lightning to this library for now. It has its own trainer that supports distributed training, device management and custom callbacks. However, I am open to changes. In particular, is there any particular features available in lightning that is missing here and you would like to be implemented?
