### ISSUE TITLE
PixelCNNSampler Trained Model Deletion

### ISSUE THREAD

**Issue by willxxy** [clementchadebec/benchmark_VAE#146]
Hello,

Thank you for providing this fantastic repository.

I noticed that after fitting my PixelCNN model, in `pythae/samplers/pixelcnn_sampler/pixelcnn_sampler.py` it seems to delete the training directory after fitting. 

This is in lines 153 - 157 in the file
```
trainer.train()

self.pixelcnn_model = PixelCNN.load_from_folder(
    os.path.join(trainer.training_dir, "final_model")
).to(self.device)

shutil.rmtree(trainer.training_dir) # in this line

self.is_fitted = True
```

Is this intended?

**Comment by clementchadebec** [comment]
Hello, 

Thank you for the kind words! This is indeed the intended usage to avoid creating folders on the user's machine. If you want to save the model weights after fitting it, you can still do it using the `save` method for the `PixelCNNModel`
```python
# save sampler weights after fitting 
fitted_sampler.pixelcnn_model.save("path_to_save")

# reload weights
sampler.pixelcnn_model = PixelCNN.load_from_folder("path_to_save")
# Avoid raising an error when calling the `sample` method that expects `fit` to be called before
sampler.is_fitted = True
```

**Comment by willxxy** [comment]
Yes, thank you so much!
