### ISSUE TITLE
PixelCNNSampler sample function bug

### ISSUE THREAD

**Issue by willxxy** [clementchadebec/benchmark_VAE#147]
Hello again,

Thanks again for the great work. I had another question in regards to the sampling function inside of the PixelCNNSampler located in `pythae/samplers/pixelcnn_sampler`. I noticed that in line 206, the following line:

```
 z_quant = self.model.quantizer.embeddings(z.reshape(z.shape[0], -1).long())
```

gives the following bug:

```
Saved final model in my_model/PixelCNN_training_2024-07-13_17-00-00/final_model
Traceback (most recent call last):
  File "pixelcnn_fit.py", line 36, in <module>
    main()
  File "pixelcnn_fit.py", line 32, in main
    gen_samples = pixel_cnn.sample(10, 1)
  File "/mnt/data2/william/benchmark_VAE/src/pythae/samplers/pixelcnn_sampler/pixelcnn_sampler.py", line 206, in sample
    z_quant = self.model.quantizer.embeddings(z.reshape(z.shape[0], -1).long())
TypeError: 'Tensor' object is not callable
```

which makes sense since `self.model.quantizer.embeddings` is the embeddings themselves. I believe what has to be done since z are the learned, sampled indices by pixelcnn, you should be indexing the embeddings instead like so:

```
z_quant = self.model.quantizer.embeddings[z.reshape(z.shape[0], -1).long()]
```

With this change, I was able to get sensible generations from the pixel cnn sampler. If this is correct, I would be happy to file a PR for these changes.

**Comment by clementchadebec** [comment]
Hello, thanks for raising this issue, I have never encountered this one. The tests related to this sampler seemed to pass (https://github.com/clementchadebec/benchmark_VAE/blob/main/tests/test_pixelcnn_sampler.py) so maybe this is due to a pytorch change. Which  version do you use?

**Comment by willxxy** [comment]
Hello,

I am currently using pytorch 1.12.1+cu113. I thought this was okay since the requirements is that >=1.10.1

**Comment by clementchadebec** [comment]
Yes that should be fine indeed.. I will try to reproduce the bug with your setting since it seemed to work with `torch=2.3`

**Comment by willxxy** [comment]
Ok thank you so much!

**Comment by clementchadebec** [comment]
I was able to reproduce the issue.

It seems the error only arises when using the `QuantizerEMA` (*i.e.* using EMA in the VQVAE) since in that case the embeddings are indeed tensors. When using `Quantizer` the embeddings are instances of `torch.nn.Embedding` that can be called as done in the sampler. 

Thanks for catching this and for proposing a fix :)  I think what you propose looks good but should be completed by the following since it will not work if the embeddinsg are  a `torch.nn.Embedding` instance

```python
 if isinstance(self.model.quantizer.embeddings, torch.Tensor):
     z_quant = self.model.quantizer.embeddings[
     z.reshape(z.shape[0], -1).long()
]
else:
    z_quant = self.model.quantizer.embeddings(
    z.reshape(z.shape[0], -1).long()
)
```

Let me know what you think :)
