### ISSUE TITLE
RHVAE error: mat1 and mat2 shapes cannot be multiplied

### ISSUE THREAD

**Issue by shannjiang** [clementchadebec/benchmark_VAE#4]
Hi,

I am trying to use RHVAE to perform data augmentation but got an error:
ModelError: Error when calling forward method from model. Potential issues: 
 - Wrong model architecture -> check encoder, decoder and metric architecture if you provide yours 
 - The data input dimension provided is wrong -> when no encoder, decoder or metric provided, a network is built automatically but requires the shape of the flatten input data.
Exception raised: <class 'RuntimeError'> with message: mat1 and mat2 shapes cannot be multiplied (2x16384 and 1024x10)

The input dimension for my data is [1,79,79] instead of [1,28,28] as in the tutorial.

Every parameter in my model is the same as the tutorial except the input_dim parameter:
config = BaseTrainingConfig(
    output_dir='my_model',
    learning_rate=1e-4,
    batch_size=100,
    num_epochs=100,
)

model_config = RHVAEConfig(
    input_dim=(1, 79, 79),
    latent_dim=10,
    n_lf=1,
    eps_lf=0.001,
    beta_zero=0.3,
    temperature=1.5,
    regularization=0.001

)

model = RHVAE(
    model_config=model_config,
    encoder=Encoder_VAE_MNIST(model_config), 
    decoder=Decoder_AE_MNIST(model_config) 
)

Any idea how to modify the code to run it?

**Comment by shannjiang** [comment]
Hey @clementchadebec ,

Thank you so much for the prompt reply! The code is working fine now with built-in autoencoder turned off. Actually my original data is one dimensional. Thank you for point me to the notebook which I can refer! I can build a conv1d autoencoder to fit my data with the notebook. I will compare between the MLP and my 1D autoencoder.

Thanks,
Shan

**Comment by clementchadebec** [comment]
Hi Shan,

Thanks for letting me know! Happy to see that you were able to make it work in your case.
I will close this issue since it seems resolved. Do not hesitate to reopen it if you have any question.

Best,
Clément
