### ISSUE TITLE
Model Request: Poincare VAE

### ISSUE THREAD

**Issue by tomhosking** [clementchadebec/benchmark_VAE#40]
It would be great to see the Poincare VAE (or a similar hyperbolic geometry VAE) implemented in pythae!

Paper: https://arxiv.org/abs/1901.06033
Code: https://github.com/emilemathieu/pvae

**Comment by clementchadebec** [comment]
Hi @tomhosking,

Thank you for this suggestion! Yes indeed, I think having this model in `pythae` would be very cool :). However, I am not sure if I can integrate it in the next few days. This library is nevertheless open to new contributors and if anyone wants to give it a try, they are more than welcome! :)

I will keep this issue open until the model is added.

Best,

Clément

**Comment by clementchadebec** [comment]
Hi @tomhosking,

I have just merged #51 containing a implementation of the PoincaréVAE proposed in https://arxiv.org/abs/1901.06033. You will also find a [tutorial](https://colab.research.google.com/github/clementchadebec/benchmark_VAE/blob/main/examples/notebooks/models_training/pvae_training.ipynb) and some [reproduced results](https://github.com/clementchadebec/benchmark_VAE/tree/main/examples/scripts/reproducibility).

Let me know if you have any questions on the implementation or tutorial.

Best,

Clément

**Comment by tomhosking** [comment]
Amazing, thank you!
