### ISSUE TITLE
Compatibility with open source and free experiment tracking tool

### ISSUE THREAD

**Issue by Sinnaeve** [clementchadebec/benchmark_VAE#44]
The Readme provide instructions on how to connect to Wandb, but Wandb is not free for commercial use.
Instructions and eventual code to use at least one other monitoring tool like MlFlow would be great.

**Comment by clementchadebec** [comment]
Hi @Sinnaeve,

Further to your request, I have been working on the integration of `mlflow` as experiment monitoring tool. I have opened #48 where you will find in particular a [tutorial](https://github.com/clementchadebec/benchmark_VAE/blob/mlflow/examples/notebooks/mlflow_experiment_monitoring.ipynb) showing how to connect to `mlflow` using `pythae`. See also the updated README.

Let me know through #48 if the tutorial is clear enough or if further elements should be added :)

Best,

Clément
