### ISSUE TITLE
Comet for Experiment Tracking 

### ISSUE THREAD

**Issue by sherpan** [clementchadebec/benchmark_VAE#55]
**Is your feature request related to a problem? Please describe.**
I want to be able to compare my reconstructed Images across multiple runs 

**Describe the solution you'd like**
Flexibility to select Comet as my tracking tool

**Comment by clementchadebec** [comment]
Hi @sherpan,

Thank you for opening this issue! I have just opened this PR #56 integrating `comet_ml` to the library. Do not hesitate to let me know if this is the expected behavior. If so I will merge and make a release.

Best,

Clément
