### ISSUE TITLE
Can't install due to pickle5 dependency

### ISSUE THREAD

**Issue by VolodyaCO** [clementchadebec/benchmark_VAE#58]
**Describe the bug**

pickle5 backports things from the future. But it does not exist in newer python versions:

```zsh
package pickle5-0.0.10-py37h8f50634_0 requires python >=3.7,<3.8.0a0, but none of the providers can be installed
```

**To Reproduce**
Use python 3.8.13 and try to install the library with micromamba.

**Expected behavior**
To correctly install and import the library.

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur - Apple M1 chip

**Comment by clementchadebec** [comment]
Hi @VolodyaCO,

Thank you for opening this issue. I just tried with your specific python version (3.8.13) on my end and it worked just fine with `pip`,  `conda-forge` and using `micromamba install pythae -c conda-forge`. Have you specified the `conda-forge` channel?

Best,

Clément

**Comment by VolodyaCO** [comment]
Hi, I was unable to install `pickle5`, through the `-c conda-forge`. I should have added the fact that I was able to install `pythae` but when I imported, the import failed due to cloudpickle not being installed. Then I installed cloudpickle again, and the error now was that pickle5 was not found. Hence the solution in #59
