### ISSUE TITLE
Nan values in loss with SVAE

### ISSUE THREAD

**Issue by ravih18** [clementchadebec/benchmark_VAE#72]
Hello @clementchadebec

It's me again. I am trying to use SVAE but I have the following issue:
```
ArithmeticError: NaN detected in train loss
```

I tried to get at the root of it, and it appears that the ive function computed by scipy returns me a vector full of 0. Then this ive value is used as a denominator to compute term1 of the kl_divergence, which gives me Nan

I have the following input values: 
* `m=128` which is the size of my latent space if I understand well, 
*  `concentration=([1.7261], [1.5885], [1.5459], [1.4761], [1.7366], [1.8380], [1.7711], [1.6688], [1.7780], [1.6073], [1.6243], [1.7058], [1.7223], [1.8469], [1.7381], [1.7835], [1.6530], [1.7053], [1.6378], [1.7360], [2.0845], [1.5052], [1.6371], [1.6176])`, which is a tuple of value between 1 and 2 of the size `batch_size`.

Does you think that it may come from incorrect values of concentration ? 

My encoder architecture is the following:
```
Sequential(
  (0): Encoder(
    (layers): Sequential(
      (0): EncoderLayer3D(
        (layer): Sequential(
          (0): Conv3d(1, 32, kernel_size=(4, 4, 4), stride=(2, 2, 2), padding=(1, 1, 1), bias=False)
          (1): BatchNorm3d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
      (1): EncoderLayer3D(
        (layer): Sequential(
          (0): Conv3d(32, 64, kernel_size=(4, 4, 4), stride=(2, 2, 2), padding=(1, 1, 1), bias=False)
          (1): BatchNorm3d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
      (2): EncoderLayer3D(
        (layer): Sequential(
          (0): Conv3d(64, 128, kernel_size=(4, 4, 4), stride=(2, 2, 2), padding=(1, 1, 1), bias=False)
          (1): BatchNorm3d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
      (3): Flatten()
    )
    (mu_layer): Linear(in_features=153600, out_features=128, bias=True)
    (log_concentration): Linear(in_features=153600, out_features=1, bias=True)
  )
```

I will keep looking on my side.
Best,

**Comment by clementchadebec** [comment]
Hi @ravih18,
Thank you for opening this issue! This is also something I noticed when I tried with latent spaces of higher dimension. I am not sure where the error comes from since I got the same error with the [official implementation](https://github.com/nicola-decao/s-vae-pytorch) (using MNIST and a latent space of dimension 64). Maybe this is a limitation of the method since the samplings are no longer straightforward and may cause instabilities).
